---
services:
    mongo-db:
        image: mongo:8.0-rc
        volumes:
            - ./mongo-data:/data/db
        ports:
            - 27017:27017
    rabbitmq:
        image: rabbitmq:3.13
        ports:
            - 5672:5672
    react-frontend:
        build:
            context: ./
            dockerfile: ./Dockerfile-react
        depends_on:
            - mongo-db
        ports:
            - 3000:3000
        volumes:
            - ./frontend/src:/react-app/src
        environment:
            - WDS_SOCKET_HOST=127.0.0.1
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
    django-backend:
        build:
            context: ./
            dockerfile: ./Dockerfile-django
        depends_on:
            - mongo-db
            - rabbitmq
            - react-frontend
        ports:
            - 8000:8000
    worker:
        build:
            context: ./
            dockerfile: ./Dockerfile-worker
        command: celery -A pet.pes_task worker --loglevel=INFO
        depends_on:
            - mongo-db
            - rabbitmq
            - django-backend
        deploy:
            replicas: 1
